// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcpGsQdznLcZ6dY7Peu0ppvJtX3qh24OY',
    appId: '1:8836614685:web:3684d3848279201c2554f4',
    messagingSenderId: '8836614685',
    projectId: 'flutter-ee33d',
    authDomain: 'flutter-ee33d.firebaseapp.com',
    storageBucket: 'flutter-ee33d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvHKdRd5UPuCnsOF_ajBknuDIACOTXm2A',
    appId: '1:8836614685:android:f6c02d09aed9fe542554f4',
    messagingSenderId: '8836614685',
    projectId: 'flutter-ee33d',
    storageBucket: 'flutter-ee33d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDScYOihQG5RLn7I6t5eRqf2CAGepkCRzc',
    appId: '1:8836614685:ios:45aafb31795552e12554f4',
    messagingSenderId: '8836614685',
    projectId: 'flutter-ee33d',
    storageBucket: 'flutter-ee33d.firebasestorage.app',
    iosBundleId: 'com.example.tp5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDScYOihQG5RLn7I6t5eRqf2CAGepkCRzc',
    appId: '1:8836614685:ios:45aafb31795552e12554f4',
    messagingSenderId: '8836614685',
    projectId: 'flutter-ee33d',
    storageBucket: 'flutter-ee33d.firebasestorage.app',
    iosBundleId: 'com.example.tp5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcpGsQdznLcZ6dY7Peu0ppvJtX3qh24OY',
    appId: '1:8836614685:web:8748e4cddfc2f72f2554f4',
    messagingSenderId: '8836614685',
    projectId: 'flutter-ee33d',
    authDomain: 'flutter-ee33d.firebaseapp.com',
    storageBucket: 'flutter-ee33d.firebasestorage.app',
  );
}
